default: &default
  adapter: postgresql
  host: localhost
  username: tanya
  password: secret
  encoding: unicode

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'task_manager_development' %>

test:
  <<: *default
  database: task_manager_test
  port: <%= (ENV['CI_NAME'] == 'codeship') ? 5433 : 5432 %>

production:
  <<: *default
  database: task_manager_production
  username: tanya
  password: secret
  host: localhost
  port: 5432